config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description,
      :price_per_night, :number_of_guests)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price_per_night %>
    <%= f.text_field :price_per_night, class: 'form-control' %>
  </div>

 <div class="form-group">
    <%= f.label :number_of_guests %>
    <%= f.text_field :number_of_guests, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/flats/_navbar.html.erb
<div class="navbar">
  <p>SimpleAirBnB</p>
  <a href="#news">Add a new flat</a>
</div>

app/views/flats/index.html.erb
<%= render 'navbar' %>

<h1>All our flats</h1>

<% @flats.each do |flat| %>
  <div class=card>
    <h2><%= flat.name %></h2>
    <p><%= flat.address %></p>
    <p><%= flat.price_per_night %></p>
    <p><%= flat.number_of_guests %></p>
    <p><%= link_to 'More info', @flat %></p>
  </div>
<% end %>

app/views/flats/new.html.erb
<h1>Add a flat</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
xxx

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>